
# repository:
#   # See https://developer.github.com/v3/repos/#edit for all available settings.

#   # The name of the repository. Changing this will rename the repository
#   name: ProbotTestRepo

#   # A short description of the repository that will show up on GitHub
#   description: description of repo is test

#   # A URL with more information about the repository
#   homepage: https://example.github.io/

#   # A comma-separated list of topics to set on the repository
#   topics: github, probot

#   # Either `true` to make the repository private, or `false` to make it public.
#   private: false

#   # Either `true` to enable issues for this repository, `false` to disable them.
#   has_issues: true

#   # Either `true` to enable projects for this repository, or `false` to disable them.
#   # If projects are disabled for the organization, passing `true` will cause an API error.
#   has_projects: true

#   # Either `true` to enable the wiki for this repository, `false` to disable it.
#   has_wiki: true

#   # Either `true` to enable downloads for this repository, `false` to disable them.
#   has_downloads: true

#   # Updates the default branch for this repository.
#   default_branch: master

#   # Either `true` to allow squash-merging pull requests, or `false` to prevent
#   # squash-merging.
#   allow_squash_merge: true

#   # Either `true` to allow merging pull requests with a merge commit, or `false`
#   # to prevent merging pull requests with merge commits.
#   allow_merge_commit: true

#   # Either `true` to allow rebase-merging pull requests, or `false` to prevent
#   # rebase-merging.
#   allow_rebase_merge: true

# # Labels: define labels for Issues and Pull Requests
# labels:
#   - name: bug
#     color: FFFF33
#   - name: feature
#     color: 336699
#   # - name: first-timers-only
#   #   # include the old name to rename an existing label
#   #   oldname: Help Wanted

# # Collaborators: give specific users access to this repository.
# # collaborators:
# #   - username: bkeepers
# #     # Note: Only valid on organization-owned repositories.
# #     # The permission to grant the collaborator. Can be one of:
# #     # * `pull` - can pull, but not push to or administer this repository.
# #     # * `push` - can pull and push, but not administer this repository.
# #     # * `admin` - can pull, push and administer this repository.
# #     permission: push

# #   - username: hubot
# #     permission: pull

# # NOTE: The APIs needed for teams are not supported yet by GitHub Apps
# # https://developer.github.com/v3/apps/available-endpoints/
# teams:
#   - name: cor
#     permission: admin
#   - name: doc
#     permission: push

milestones:
  - title: Hello issue (Milestone)
    description: Changed description of Hello Issue
    due_on: 2018-03-29T8:00:00Z
    state: closed
  - title: Milestone Test
    description: mileston test description
    due_on: 2019-04-21T7:55:42Z
    state: open

# labels:
#   - name: bug
#     color: CC0000
#   - name: feature
#     color: 336699
#   - name: new-modification
#     color: 336699